package org.grails.cxf.soap.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2016-03-08T15:30:24.204+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.msssi.es/catalogo/base/", name = "ServicioServices")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicioServices {

    @RequestWrapper(localName = "updateServicioByEstado", targetNamespace = "http://www.msssi.es/catalogo/base/", className = "org.grails.cxf.soap.UpdateServicioByEstado")
    @WebMethod
    @ResponseWrapper(localName = "updateServicioByEstadoResponse", targetNamespace = "http://www.msssi.es/catalogo/base/", className = "org.grails.cxf.soap.UpdateServicioByEstadoResponse")
    public void updateServicioByEstado(
        @WebParam(name = "estado", targetNamespace = "")
        java.lang.String estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigo,
        @WebParam(mode = WebParam.Mode.OUT, name = "descripcion", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> descripcion
    );
}
