package org.grails.cxf.soap.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2016-03-08T15:30:24.213+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ServicioWebServices", 
                  wsdlLocation = "src/java/DatosServicioServices.wsdl",
                  targetNamespace = "http://www.msssi.es/catalogo/base/") 
public class ServicioWebServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.msssi.es/catalogo/base/", "ServicioWebServices");
    public final static QName ServicioServicesPort = new QName("http://www.msssi.es/catalogo/base/", "ServicioServicesPort");
    static {
        URL url = ServicioWebServices.class.getResource("src/java/DatosServicioServices.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServicioWebServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/java/DatosServicioServices.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ServicioWebServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioWebServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioWebServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioWebServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicioServices
     */
    @WebEndpoint(name = "ServicioServicesPort")
    public ServicioServices getServicioServicesPort() {
        return super.getPort(ServicioServicesPort, ServicioServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioServices
     */
    @WebEndpoint(name = "ServicioServicesPort")
    public ServicioServices getServicioServicesPort(WebServiceFeature... features) {
        return super.getPort(ServicioServicesPort, ServicioServices.class, features);
    }

}
