package org.grails.cxf.soap.estado;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2016-03-05T14:10:32.281+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/EstadoServicio", name = "EstadoServicioPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EstadoServicioPortType {

    @Oneway
    @WebMethod
    public void start(
        @WebParam(partName = "parameters", name = "start", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/EstadoServicio")
        Start parameters
    );
}
