package org.grails.cxf.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2016-02-17T12:44:32.762+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/InventarioProject/InventarioProyect/BPEL_Inventario", name = "BPEL_Inventario")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BPELInventario {

    @WebResult(name = "inventarioResponse", targetNamespace = "http://blog.soa.ejemplos/Inventario", partName = "payload")
    @WebMethod
    public InventarioResponse process(
        @WebParam(partName = "payload", name = "inventarioRequest", targetNamespace = "http://blog.soa.ejemplos/Inventario")
        InventarioRequest payload
    );
}
