package org.grails.cxf.soap;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2016-03-05T14:10:32.398+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/EstadoServicio", name = "EstadoServicioPortTypeCallBack")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EstadoServicioPortTypeCallBack {

    @Oneway
    @WebMethod
    public void end(
        @WebParam(partName = "parameters", name = "endResponse", targetNamespace = "http://xmlns.oracle.com/bpmn/bpmnProcess/EstadoServicio")
        EndResponse parameters
    );
}
