package org.grails.cxf.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2016-02-17T10:49:25.614+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ProductosWebServices", 
                  wsdlLocation = "src/java/ProductosServices.wsdl",
                  targetNamespace = "https://franl2p.wordpress.com/") 
public class ProductosWebServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://franl2p.wordpress.com/", "ProductosWebServices");
    public final static QName ProductosServicesPort = new QName("https://franl2p.wordpress.com/", "ProductosServicesPort");
    static {
        URL url = ProductosWebServices.class.getResource("src/java/ProductosServices.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ProductosWebServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/java/ProductosServices.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ProductosWebServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductosWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductosWebServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductosWebServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductosWebServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductosWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProductosServices
     */
    @WebEndpoint(name = "ProductosServicesPort")
    public ProductosServices getProductosServicesPort() {
        return super.getPort(ProductosServicesPort, ProductosServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductosServices
     */
    @WebEndpoint(name = "ProductosServicesPort")
    public ProductosServices getProductosServicesPort(WebServiceFeature... features) {
        return super.getPort(ProductosServicesPort, ProductosServices.class, features);
    }

}
